name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  native:
    strategy:
      fail-fast: false
      matrix:
        runner:
          - ubuntu-24.04
          - ubuntu-24.04-arm
          - macos-15
          - macos-15-intel
    runs-on: ${{ matrix.runner }}
    env:
      CARGO_INCREMENTAL: 0
      CARGO_TERM_COLOR: always
    steps:
      - uses: actions/checkout@v6
      - uses: dtolnay/rust-toolchain@1.91.0
        with:
          components: rustfmt, clippy
      - if: matrix.runner == 'ubuntu-24.04'
        run: cargo fmt --all -- --check
      - if: matrix.runner == 'ubuntu-24.04'
        run: cargo clippy --locked --all-targets --all-features -- -D warnings
      - if: matrix.runner == 'ubuntu-24.04'
        env:
          RUSTDOCFLAGS: -D warnings
        run: cargo doc --locked --no-deps --all-features
      - if: matrix.runner == 'ubuntu-24.04'
        run: cargo package --locked
      - run: cargo test --locked --all-features
      - run: cargo test --release --locked --all-features
